build_from:
  armv7: ghcr.io/home-assistant/armv7-base-debian:trixie-2025.11.1
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie-2025.12.0
  armhf: ghcr.io/home-assistant/armhf-base-debian:trixie-2025.11.1
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie-2025.12.0
  i386: ghcr.io/home-assistant/i386-base-debian:trixie-2025.11.1
